theme = "mytheme"

[editor]
line-number = "relative"
cursorline = true
auto-format = true
auto-save = true
completion-trigger-len = 1
idle-timeout = 0
color-modes = true
rulers = [80]
lsp.display-inlay-hints = true
gutters = ["diagnostics", "line-numbers", "diff"]
[editor.soft-wrap]
enable = true

[editor.statusline]
center = ["file-type", "workspace-diagnostics" , "version-control"]
right = ["diagnostics", "selections", "position", "file-encoding", "position-percentage", "total-line-numbers"]

[editor.whitespace]
render.tab = "all"
characters.tab = "│"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[keys.normal]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
"C-f" = ":run-shell-command tmux new-window tmux-sessionizer"

[keys.select]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

[keys.insert]
"C-a" = "goto_line_start"
"C-e" = "goto_line_end"
"C-b" = "move_char_left"
"C-f" = "move_char_right"
"A-b" = "move_prev_word_start"
"A-f" = "move_next_word_start"
