[[language]]
name = "c"
auto-format = false
indent = { tab-width = 8, unit = "\t"}

[[language]]
name = "cpp"
auto-format = false
indent = { tab-width = 8, unit = "\t"}

[[language]]
name = "diff"
indent = { tab-width = 8, unit = "\t"}

[[language]]
name = "rust"

[[language]]
name = "cpp"

[[language]]
name = "bitbake"
indent = { tab-width = 4, unit = " " }
file-types = ["bb", "bbappend", "bbclass", "conf", "inc"]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
