icons_format = "{icon}"

[theme]
theme = "solarized-light"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ""
bat_full = ""
bat_charging = "󱐋"
bat_discharging = ""

[[block]]
block = "net"
format_alt  = "$icon {$signal_strength $ssid|Wired} via $device 󰇚 $speed_down 󰕒 $speed_up"
format = "$icon {$signal_strength $ssid|Wired} via $device 󰇚 $speed_down $graph_down 󰕒 $speed_up $graph_up {$ip|$ipv6}"

[[block]]
block = "cpu"
format_alt  = " $utilization"
format = " $utilization $barchart"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format_alt  = "$icon $available"
format = "$icon $available / $total $percentage"

[[block]]
block = "memory"
format = "$icon $mem_avail"
format_alt = "$icon_swap $swap_free"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "backlight"
format = "$icon $brightness"

[[block]]
block = "battery"
format = "$icon $percentage $time $power"

[[block]]
block = "time"
interval = 5
format = "$timestamp.datetime(f:'%a %d/%m %R')"
