export PS1="\[$(tput bold)\]\[\033[38;5;0m\]\[\033[48;5;10m\]\t\[$(tput sgr0)\]{\[$(tput sgr0)\]\[\033[38;5;1m\]\u\[$(tput sgr0)\]@\[$(tput sgr0)\]\[\033[38;5;27m\]\l\[$(tput sgr0)\]\[\033[38;5;5m\]\h\[$(tput sgr0)\]}\[$(tput sgr0)\]\[\033[38;5;130m\]\w\[$(tput sgr0)\]\[\033[38;5;2m\]\$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/')\[$(tput sgr0)\]\n\[$(tput sgr0)\]\[$(tput bold)\]\[\033[38;5;0m\]\[\033[48;5;10m\]\\$\[$(tput sgr0)\] \[$(tput sgr0)\]"
PATH=$PATH:$HOME/.cargo/bin:.
alias remove='/usr/bin/rm '
alias arduino='export _JAVA_AWT_WM_NONREPARENTING=1 arduino'
alias rm='trash '
alias p='pacman '
alias fk='fuck'
alias ls='ls --color=auto'
alias d='doas '
alias pt='ping google.com'
alias rc='gcc src/main.c -o bin/main -lSDL2_ttf -lSDL2 -lm -g && ./bin/main'
alias rr='cargo run '
alias lg='lazygit '
alias ch='chromium '
alias acfU='arduino-cli compile --fqbn arduino:avr:nano src && d chmod 777 /dev/ttyUSB* && arduino-cli upload -p /dev/ttyUSB* --fqbn arduino:avr:nano src'
alias acfA='arduino-cli compile --fqbn arduino:avr:nano src && d chmod 777 /dev/ttyACM* && arduino-cli upload -p /dev/ttyACM* --fqbn arduino:avr:nano src'
alias afU='d chmod 777 /dev/ttyUSB* && arduino-cli upload -p /dev/ttyUSB* --fqbn arduino:avr:nano src'
alias afA='d chmod 777 /dev/ttyACM* && arduino-cli upload -p /dev/ttyACM* --fqbn arduino:avr:nano src'
alias ac='arduino-cli compile --fqbn arduino:avr:nano src'
alias a='xhost +SI:localuser:root && d arduino'
alias q='xhost +SI:localuser:root && cd && d ./altera/13.0sp1/quartus/bin/quartus --64bit'
alias grep='rg'
alias hx='helix'
alias hr='nvim src/main.rs $(find src -type f) $(find lib -type f)'
