export PS1="[\A]\w\$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/')\\$ \[$(tput sgr0)\]"
alias p='pacman'
alias ls='ls --color=auto'
alias d='doas '
alias pt='ping google.com'
alias rc='gcc src/main.c -Wall -g -o bin/main -lm -lSDL2 -lSDL2_image && SDL_VIDEODRIVER=wayland ./bin/main'
alias rr='cargo run '
alias n='nvim'
alias lg='lazygit '
alias ch='chromium '
alias nr='nvim src/main.rs src/* *.toml'
alias nc='nvim src/main.c src/*'
alias na='nvim src/src.ino'
alias af='d chmod 777 /dev/ttyUSB* && arduino-cli upload -p /dev/ttyUSB* --fqbn arduino:avr:leonardo src'
alias ac='arduino-cli compile --fqbn arduino:avr:leonardo src'
alias a='xhost +SI:localuser:root && d arduino'
alias q='xhost +SI:localuser:root && cd && d ./altera/13.0sp1/quartus/bin/quartus --64bit'
