export PS1="[\t]\w\$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/')\\$ \[$(tput sgr0)\]"
alias p='pacman'
alias ls='ls --color=auto'
alias d='doas '
alias pt='ping google.com'
alias rc='gcc src/main.c -Wall -g -o bin/main -lm -lSDL2 -lSDL2_image && SDL_VIDEODRIVER=wayland ./bin/main'
alias rr='cargo run '
alias n='neovide --multigrid'
alias lg='lazygit '
alias ch='chromium '
alias nr='neovide --multigrid src/main.rs $(find src -type f) *.toml'
alias np='neovide --multigrid boards/rp-pico/mine/*.rs'
alias nc='neovide --multigrid src/main.c $(find src -type f)'
alias rc='gcc src/main.c -o bin/main -lSDL2 -lm -g && ./bin/main'
alias af='d chmod 777 /dev/ttyUSB* && arduino-cli upload -p /dev/ttyUSB* --fqbn arduino:avr:leonardo src'
alias ac='arduino-cli compile --fqbn arduino:avr:leonardo src'
alias a='xhost +SI:localuser:root && d arduino'
alias q='xhost +SI:localuser:root && cd && d ./altera/13.0sp1/quartus/bin/quartus --64bit'
